export interface Secrets {
  COMMERCETOOLS_CLIENT_ID: string
  COMMERCETOOLS_SECRET: string
  CONTENTFUL_TOKEN: string
  PORTAL_API_STARKIS_CLIENT_ID: string
  PORTAL_API_STARKIS_CLIENT_SECRET: string
  PORTAL_API_AUTH0_CLIENT_ID: string
  PORTAL_API_AUTH0_SECRET: string
  PORTAL_API_CHARGEBEE_API_KEY: string
}
